CREATE TABLE CONSUMO 
(
  ID NUMBER(*, 0) NOT NULL 
, VALOR NUMBER(*, 0) 
, FECHAREGISTRO DATE NOT NULL 
, NUMEROHABITACIONACARGAR VARCHAR2(20 BYTE) NOT NULL 
, IDSERVICIOCARGADO NUMBER NOT NULL 
, CONSTRAINT CONSUMO_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONSUMO_PK ON CONSUMO (ID ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE CONSUMO
ADD CONSTRAINT CONSUMO_FK1 FOREIGN KEY
(
  NUMEROHABITACIONACARGAR 
)
REFERENCES HABITACION
(
  NUMERO 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE CONSUMO
ADD CONSTRAINT CONSUMO_FK2 FOREIGN KEY
(
  IDSERVICIOCARGADO 
)
REFERENCES SERVICIO
(
  ID 
)
ON DELETE CASCADE ENABLE;

CREATE TABLE HABITACION 
(
  NUMERO VARCHAR2(20 BYTE) NOT NULL 
, TIPOHABITACION VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT HABITACION_PK PRIMARY KEY 
  (
    NUMERO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX HABITACION_PK ON HABITACION (NUMERO ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE HABITACION
ADD CONSTRAINT HABITACION_FK1 FOREIGN KEY
(
  TIPOHABITACION 
)
REFERENCES TIPOHABITACION
(
  NOMBRE 
)
ON DELETE CASCADE ENABLE;

CREATE TABLE PLANCONSUMO 
(
  NOMBRE VARCHAR2(20 BYTE) NOT NULL 
, PORCENTAJEDESCUENTO NUMBER NOT NULL 
, DESCRIPCION VARCHAR2(400 BYTE) 
, CONSTRAINT PLANCONSUMO_PK PRIMARY KEY 
  (
    NOMBRE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PLANCONSUMO_PK ON PLANCONSUMO (NOMBRE ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE PRODUCTO 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, NOMBRE VARCHAR2(20 BYTE) NOT NULL 
, DURACION NUMBER 
, IDSERVICIO NUMBER NOT NULL 
, CONSTRAINT PRODUCTO_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PRODUCTO_PK ON PRODUCTO (ID ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE PRODUCTO
ADD CONSTRAINT PRODUCTO_FK1 FOREIGN KEY
(
  IDSERVICIO 
)
REFERENCES SERVICIO
(
  ID 
)
ON DELETE CASCADE ENABLE;

CREATE TABLE RESERVA 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, METODODEPAGO VARCHAR2(20 BYTE) NOT NULL 
, CANTIDADPERSONAS NUMBER NOT NULL 
, FECHACOMIENZO TIMESTAMP(6) NOT NULL 
, FECHAFIN TIMESTAMP(6) NOT NULL 
, TIPOHABITACION VARCHAR2(20 BYTE) 
, PLANCONSUMO VARCHAR2(20 BYTE) 
, IDUSUARIO VARCHAR2(20 BYTE) NOT NULL 
, IDPRODUCTO VARCHAR2(20 BYTE) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TABLE1_PK ON RESERVA (ID ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_FK1 FOREIGN KEY
(
  IDUSUARIO 
)
REFERENCES USUARIO
(
  NUMERODOCUMENTO 
)
ENABLE;

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_FK2 FOREIGN KEY
(
  TIPOHABITACION 
)
REFERENCES TIPOHABITACION
(
  NOMBRE 
)
ENABLE;

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_FK3 FOREIGN KEY
(
  PLANCONSUMO 
)
REFERENCES PLANCONSUMO
(
  NOMBRE 
)
ENABLE;

ALTER TABLE RESERVA
ADD CONSTRAINT RESERVA_FK4 FOREIGN KEY
(
  IDPRODUCTO 
)
REFERENCES PRODUCTO
(
  ID 
)
ON DELETE CASCADE ENABLE;

CREATE TABLE ROLDEUSUARIO 
(
  CARGO VARCHAR2(20 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT ROLDEUSUARIO_PK PRIMARY KEY 
  (
    CARGO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ROLDEUSUARIO_PK ON ROLDEUSUARIO (CARGO ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE SERVICIO 
(
  ID NUMBER(*, 0) NOT NULL 
, NOMBRE VARCHAR2(20 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(400 BYTE) 
, COSTO NUMBER(*, 0) 
, CONSTRAINT SERVICIO_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SERVICIO_PK ON SERVICIO (ID ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE TIPOHABITACION 
(
  NOMBRE VARCHAR2(20 BYTE) NOT NULL 
, CAPACIDAD NUMBER(*, 0) NOT NULL 
, CANTIDADDISPONIBLE NUMBER(*, 0) NOT NULL 
, COSTOPORNOCHE NUMBER(*, 0) NOT NULL 
, CONSTRAINT TIPOHABITACION_PK PRIMARY KEY 
  (
    NOMBRE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TIPOHABITACION_PK ON TIPOHABITACION (NOMBRE ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE USUARIO 
(
  NOMBRE VARCHAR2(20 BYTE) NOT NULL 
, ROL VARCHAR2(20 BYTE) NOT NULL 
, EDAD NUMBER NOT NULL 
, TELEFONO VARCHAR2(20 BYTE) NOT NULL 
, TIPODOCUMENTO VARCHAR2(20 BYTE) NOT NULL 
, NUMERODOCUMENTO VARCHAR2(20 BYTE) NOT NULL 
, CORREO VARCHAR2(20 BYTE) NOT NULL 
, FECHALLEGADA VARCHAR2(20 BYTE) 
, FECHASALIDA VARCHAR2(20 BYTE) 
, NUMEROHABITACION VARCHAR2(20 BYTE) 
, CONSTRAINT USUARIO_PK PRIMARY KEY 
  (
    NUMERODOCUMENTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USUARIO_PK1 ON USUARIO (NUMERODOCUMENTO ASC) 
      NOLOGGING 
      TABLESPACE TBSPROD 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
NOLOGGING 
TABLESPACE TBSPROD 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE USUARIO
ADD CONSTRAINT USUARIO_FK1 FOREIGN KEY
(
  ROL 
)
REFERENCES ROLDEUSUARIO
(
  CARGO 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE USUARIO
ADD CONSTRAINT USUARIO_FK2 FOREIGN KEY
(
  NUMEROHABITACION 
)
REFERENCES HABITACION
(
  NUMERO 
)
ON DELETE CASCADE ENABLE;
